### ISSUE TITLE
Can't find File "/github/workspace/clover.xml"

### ISSUE THREAD

**Issue by skywarth** [timkrase/phpunit-coverage-badge#13]
Exact same issue with the #11 

My workflow is like so:

```
jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@####
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: phpunit-coverage-badge
      uses: timkrase/phpunit-coverage-badge@v1.2.0
```

Only possible difference between #11 that I can see is: I use checkout@v3 opposed to the documentaion which demonstrates with checkout@v2. Or maybe it is the PHP version that is causing the problem. Either way I'm confused. 

I also attempted it by giving your action `report` parameter for clover file, no chance. 

Can you help me with this ? Thanks.

Update: changed `actions/checkout@v3` usage to `actions/checkout@v2`, made no visible difference, still got the same error: `Fatal error: Uncaught Assert\InvalidArgumentException: File "/github/workspace/clover.xml" was expected to exist. in /srv/vendor/beberlei/assert/lib/Assert/Assertion.php:2725`
