### ISSUE TITLE
Alternate configuration that avoids regular git pulls

### ISSUE THREAD

**Issue by 8ctopus** [timkrase/phpunit-coverage-badge#19]
Hi Tim,

Thank you for the nice action, I would suggest adjusting the readme a bit to make it easier to use. Let me explain, now on every push, the action runs, creates the badge and makes a new commit on the master branch. That's causing some problems because I always need to pull the latest changes from remote before I can push (I use git pull --rebase for that purpose). 

There's another possibility which doesn't create that problem:

```yml
      - name: Make code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: output/coverage.svg
          # push badge later on
          push_badge: false
 
      - name: Git push to image-data branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
```
