### ISSUE TITLE
CI Skip by default 

### ISSUE THREAD

**Issue by MikeDevresse** [timkrase/phpunit-coverage-badge#7]
Commiting that the badge is changing is triggering github actions to run again. I don't know if you can configure that in your github action but maybe adding documentation may do the job. I found that if you add the following line and you add [ci skip] in your commit then it might skip the github action. 

```
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
```
